import { CartProvider } from "./context/CartContext";
import { AddressProvider } from "./context/AddressContext";
import { FavoritesProvider } from "./context/FavoritesContext";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased font-sans" suppressHydrationWarning>
        <CartProvider>
          <AddressProvider>
            <FavoritesProvider>
              {children}
            </FavoritesProvider>
          </AddressProvider>
        </CartProvider>
      </body>
    </html>
  );
}
